### PR TITLE
Created New Student Profile API

### PR DESCRIPTION
**Pull request by osagiestar**
created POST Request for new student profile API - completed

### CODE REVIEW

**Review by Denis-Andrei — APPROVED** [review]
Looks good. Even if the this was a optional task, Thanks Osagie

**Review by ISTANBULBEKLE — APPROVED** [review]
Good, job, guys.

**Comment by ISTANBULBEKLE** [comment]
Osagie please continue with merging after 2 reviews.

**Review by Wolfjawan — APPROVED** [review]
LGTM

**Pull request merged**
